import { InputRule } from 'prosemirror-inputrules';
import { Schema } from 'prosemirror-model';
export declare const quotes: (schema: Schema) => InputRule<any>[];
export declare const ellipsis: (schema: Schema) => InputRule<any>[];
export declare const blockquote: (schema: Schema) => InputRule<Schema<any, any>>[];
export declare const arrows: (schema: Schema) => InputRule<any>[];
export declare const emdash: (schema: Schema) => InputRule<any>[];
export declare const copyright: (schema: Schema) => InputRule<any>[];
export declare const link: (schema: Schema) => InputRule<any>[];
export declare const lists: (schema: Schema) => InputRule<Schema<any, any>>[];
export declare const codeBlock: (schema: Schema) => InputRule<Schema<any, any>>[];
export declare const codeInline: (schema: Schema) => InputRule<any>[];
export declare const strong: (schema: Schema) => InputRule<any>[];
export declare const strikethrough: (schema: Schema) => InputRule<any>[];
export declare const em: (schema: Schema) => InputRule<any>[];
export declare const headings: (schema: Schema, maxLevel?: number) => InputRule<Schema<any, any>>[];
export declare const equation: (schema: Schema) => InputRule<any>[];
export declare const mathInline: (schema: Schema) => InputRule<any>[];
export declare const hr: (schema: Schema) => InputRule<any>[];
export declare const slider: (schema: Schema) => InputRule<any>[];
export declare const dynamic: (schema: Schema) => InputRule<any>[];
