import { InputRule } from 'prosemirror-inputrules';
import { Schema } from 'prosemirror-model';
export declare const quotes: (schema: Schema) => readonly InputRule[];
export declare const ellipsis: (schema: Schema) => InputRule[];
export declare const blockquote: (schema: Schema) => InputRule[];
export declare const arrows: (schema: Schema) => InputRule[];
export declare const emojis: (schema: Schema) => InputRule[];
export declare const fractions: (schema: Schema) => InputRule[];
export declare const emdash: (schema: Schema) => InputRule[];
export declare const copyright: (schema: Schema) => InputRule[];
export declare const link: (schema: Schema) => InputRule[];
export declare const lists: (schema: Schema) => InputRule[];
export declare const codeBlock: (schema: Schema) => InputRule[];
export declare const strong: (schema: Schema) => InputRule[];
export declare const strikethrough: (schema: Schema) => InputRule[];
export declare const em: (schema: Schema) => InputRule[];
export declare const headings: (schema: Schema, maxLevel?: number) => InputRule[];
export declare const equation: (schema: Schema) => InputRule[];
export declare const mathInline: (schema: Schema) => InputRule[];
export declare const hr: (schema: Schema) => InputRule[];
export declare const slider: (schema: Schema) => InputRule[];
