export var INIT_EDITOR_STATE = 'INIT_EDITOR_STATE';
export var SUBSCRIBE_EDITOR_VIEW = 'SUBSCRIBE_EDITOR_VIEW';
export var UNSUBSCRIBE_EDITOR_VIEW = 'UNSUBSCRIBE_EDITOR_VIEW';
export var UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
//# sourceMappingURL=types.js.map